import type { WorkAutomationSource, WorkChannel, WorkItem, WorkReviewSnapshot } from "./types";

const stamp = "2026-09-09T17:30:00.000Z";

export const previewChannels: WorkChannel[] = [
  {
    id: "preview-video",
    client_id: "abk-labs",
    name: "Video Queue",
    slug: "video-queue",
    description: "Videos moving from edit through client review and publication.",
    source_kind: "slack",
    external_ref: "ext-abk-video",
    active: true,
    created_by_user_id: "preview-user",
    created_at: stamp,
    updated_at: stamp,
  },
  {
    id: "preview-content",
    client_id: "abk-labs",
    name: "Content Schedule",
    slug: "content-schedule",
    description: "Upcoming articles, social posts, and campaign handoffs.",
    source_kind: "manual",
    external_ref: null,
    active: true,
    created_by_user_id: "preview-user",
    created_at: stamp,
    updated_at: stamp,
  },
  {
    id: "preview-meetings",
    client_id: "abk-labs",
    name: "Meeting Follow-ups",
    slug: "meeting-follow-ups",
    description: "Decisions and next steps captured from ABK and CircleClick meetings.",
    source_kind: "google_meet",
    external_ref: null,
    active: true,
    created_by_user_id: "preview-user",
    created_at: stamp,
    updated_at: stamp,
  },
];

export const previewSources: WorkAutomationSource[] = [
  {
    id: "preview-source-slack",
    client_id: "abk-labs",
    channel_id: "preview-video",
    source_kind: "slack",
    workspace_ref: "circleclick",
    source_ref: "C0BE2423W75",
    display_name: "#ext-abk-video",
    active: true,
    default_client_visible: true,
    last_ingested_at: stamp,
    created_by_user_id: "preview-user",
    created_at: stamp,
    updated_at: stamp,
    slack_notification_mode: "never",
    slack_notification_thread_ts: null,
  },
  {
    id: "preview-source-meet",
    client_id: "abk-labs",
    channel_id: "preview-meetings",
    source_kind: "google_meet",
    workspace_ref: "circleclick",
    source_ref: "abk-weekly",
    display_name: "ABK weekly Google Meet",
    active: true,
    default_client_visible: false,
    last_ingested_at: stamp,
    created_by_user_id: "preview-user",
    created_at: stamp,
    updated_at: stamp,
    slack_notification_mode: "never",
    slack_notification_thread_ts: null,
  },
];

export const previewItems: WorkItem[] = [
  {
    id: "preview-item-1",
    client_id: "abk-labs",
    channel_id: "preview-video",
    title: "Founder interview cutdown",
    now_text: "Award is tightening the 60-second edit and replacing two B-roll shots.",
    next_text: "Send the revised cut to ABK for a single approval pass.",
    blocker_text: null,
    owner_name: "Award",
    owner_user_id: null,
    status: "in_progress",
    due_date: "2026-09-11",
    source_kind: "slack",
    source_url: "https://example.com/slack/source",
    source_external_id: "preview-slack-1",
    source_snapshot_json: {},
    automation_review_needed: false,
    automation_last_seen_at: stamp,
    completion_evidence_url: null,
    client_visible: true,
    created_by_user_id: "preview-user",
    updated_by_user_id: "preview-user",
    created_at: "2026-09-08T15:00:00.000Z",
    updated_at: stamp,
    completed_at: null,
  },
  {
    id: "preview-item-2",
    client_id: "abk-labs",
    channel_id: "preview-video",
    title: "September product demo",
    now_text: "The final render is ready for client review.",
    next_text: "Publish after the title and thumbnail are approved.",
    blocker_text: "Waiting on ABK to choose the final thumbnail.",
    owner_name: "Dimitri",
    owner_user_id: "preview-user",
    status: "blocked",
    due_date: "2026-09-12",
    source_kind: "slack",
    source_url: "https://example.com/slack/source-2",
    source_external_id: "preview-slack-2",
    source_snapshot_json: {},
    automation_review_needed: false,
    automation_last_seen_at: "2026-09-09T16:10:00.000Z",
    completion_evidence_url: null,
    client_visible: true,
    created_by_user_id: "preview-user",
    updated_by_user_id: "preview-user",
    created_at: "2026-09-08T18:00:00.000Z",
    updated_at: "2026-09-09T16:10:00.000Z",
    completed_at: null,
  },
  {
    id: "preview-item-3",
    client_id: "abk-labs",
    channel_id: "preview-content",
    title: "Customer story launch post",
    now_text: "Copy and image are approved.",
    next_text: "Schedule the LinkedIn post for Thursday morning.",
    blocker_text: null,
    owner_name: "Mike",
    owner_user_id: null,
    status: "needs_evidence",
    due_date: "2026-09-10",
    source_kind: "manual",
    source_url: null,
    source_external_id: null,
    source_snapshot_json: {},
    automation_review_needed: false,
    automation_last_seen_at: null,
    completion_evidence_url: null,
    client_visible: true,
    created_by_user_id: "preview-user",
    updated_by_user_id: "preview-user",
    created_at: "2026-09-07T18:00:00.000Z",
    updated_at: "2026-09-09T14:20:00.000Z",
    completed_at: null,
  },
  {
    id: "preview-item-4",
    client_id: "abk-labs",
    channel_id: "preview-meetings",
    title: "Confirm Q4 testimonial participants",
    now_text: "The meeting produced three candidate names.",
    next_text: "ABK will confirm who can be contacted and by when.",
    blocker_text: null,
    owner_name: "ABK team",
    owner_user_id: null,
    status: "new",
    due_date: null,
    source_kind: "google_meet",
    source_url: "https://meet.google.com/",
    source_external_id: "preview-meet-1",
    source_snapshot_json: {},
    automation_review_needed: true,
    automation_last_seen_at: stamp,
    completion_evidence_url: null,
    client_visible: true,
    created_by_user_id: "preview-user",
    updated_by_user_id: "preview-user",
    created_at: stamp,
    updated_at: stamp,
    completed_at: null,
  },
];

export const previewReviewSnapshot: WorkReviewSnapshot = {
  client: { id: "abk-labs", name: "ABK Labs" },
  channel: {
    id: "preview-video",
    name: "Video Queue",
    slug: "video-queue",
    description: "Videos moving from edit through client review and publication.",
  },
  label: "ABK video progress",
  generated_at: stamp,
  items: previewItems
    .filter((item) => item.channel_id === "preview-video")
    .map((item) => ({
      id: item.id,
      title: item.title,
      now_text: item.now_text,
      next_text: item.next_text,
      blocker_text: item.blocker_text,
      owner_name: item.owner_name,
      status: item.status,
      due_date: item.due_date,
      source_url: item.source_url,
      completion_evidence_url: item.completion_evidence_url,
      updated_at: item.updated_at,
      channel_name: "Video Queue",
    })),
};
